# Generated by Django 3.2.13 on 2022-07-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackingAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='change',
        ),
    ]
