# Generated by Django 4.0.5 on 2022-07-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserBalance', '0002_alter_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='all_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='balance',
            name='all_withdraw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
