# Generated by Django 4.0.5 on 2022-07-28 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUserBalance', '0003_depositsandwithdraws_userbalance_delete_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.DateTimeField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withdraw_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='user',
        ),
        migrations.DeleteModel(
            name='DepositsAndWithdraws',
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
