# Generated by Django 4.0.5 on 2022-07-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserBalance', '0003_balance_all_deposit_balance_all_withdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='all_deposit',
            new_name='deposit_amount',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='all_withdraw',
            new_name='withdraw_amount',
        ),
    ]
