# Generated by Django 4.0.5 on 2022-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserBalance', '0004_balance_remove_userbalance_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='deposit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='withdraw_amount',
            field=models.FloatField(default=0),
        ),
    ]
