# Generated by Django 4.0.5 on 2022-07-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserBalance', '0004_rename_all_deposit_balance_deposit_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='withdraw_amount',
        ),
    ]
