# Generated by Django 4.0.5 on 2022-07-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserBalance', '0005_alter_balance_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='first_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='balance',
            name='history_balance_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
