# Generated by Django 4.0.5 on 2022-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserBalance', '0005_remove_balance_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='balance',
            name='withdraw_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
