# Generated by Django 3.2.13 on 2022-07-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='quantity',
            new_name='amount',
        ),
    ]
