# Generated by Django 3.2.13 on 2022-07-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrading', '0002_rename_quantity_trade_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
