# Generated by Django 4.0.5 on 2022-07-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrading', '0004_alter_trade_amount_alter_trade_close_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
