# Generated by Django 4.0.5 on 2022-07-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrading', '0006_trade_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
